export interface TableProps {
    default?:boolean,
    disabled?: boolean,
    headerBackground?: string,
    oddRowBackground?: string,
    evenRowBackground?: string,
    footerBackground?: string,
    caption?: string,
    heading1?: string,
    heading2?: string,
    heading3?: string,
    row1cell1?: string,
    row1cell2?: string,
    row1cell3?: string,
    row2cell1?: string,
    row2cell2?: string,
    row2cell3?: string,
    row3cell1?: string,
    row3cell2?: string,
    row3cell3?: string,
    footer1?: string,
    footer2?: string,
    footer3?: string,
}